on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo dnf -y upgrade
          sudo dnf -y install gcc make cairo-devel cairo-gobject-devel cmake bzip2-devel expat-devel file-devel glib2-devel gobject-introspection-devel libcurl-devel libmodulemd-devel libxml2-devel openssl-devel rpm-devel sqlite-devel xz-devel zchunk-devel zlib-devel python3 python3-devel python3-pip
          python3 -m pip install -r requirements.txt

      - name: Install test deps
        run: python3 -m pip install -r test_requirements.txt

      - name: Install rpmrepo
        run: python3 -m pip install .

      - name: Run tests
        run: python3 -m pytest --verbose --color=yes